#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf.nci.org.au - 2025/10/17 21:54:07
# Search URL: http://esgf.nci.org.au/esg-search/wget?dataset_id=CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r1i1p1f1.Omon.thetaoga.gn.v20200918|esg-dn2.nsc.liu.se
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf.nci.org.au/esg-search/wget?dataset_id=CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r1i1p1f1.Omon.thetaoga.gn.v20200918|esg-dn2.nsc.liu.se'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185001-185012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185001-185012.nc' 'SHA256' '3d6261f1f1a66e65d5e8f515c057efabdedf10b92394adc864c2a449f1c27113'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185101-185112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185101-185112.nc' 'SHA256' 'ccc67636f9f6dfbd392a9da9bffb7f2a23c952754683845303c3dbf7d7da9361'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185201-185212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185201-185212.nc' 'SHA256' 'a0d6dfbb4ebebb9ef2428f664bae95d00b80804dea2ad1173f6a7036f4c20bcb'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185301-185312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185301-185312.nc' 'SHA256' '4fda84910a7a0fa79e489998ad960c1a100099167a084b4190bc965d363f6265'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185401-185412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185401-185412.nc' 'SHA256' 'd475c6cdcc83fa81d4e2b12c9cca021f55910db72eaa5b7ca48a35bb3ae9425e'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185501-185512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185501-185512.nc' 'SHA256' 'ea664dc68b53c8e5cc01317e9412997e2a12f01ebb782b0ad0d07aea7061f285'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185601-185612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185601-185612.nc' 'SHA256' 'fed1cebb7e710818ae7ae2f482e8a8babfe4e5d0a31f589b0d2b6a9020ce5ca2'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185701-185712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185701-185712.nc' 'SHA256' 'a0b579453a95115e05d1c62d9fdf8d7f5b6064d45f7551f7c80187209b396c00'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185801-185812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185801-185812.nc' 'SHA256' 'a22aa1ba9255410130646165b76627be505b20942344e0d6fb4456e23cedaf68'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185901-185912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_185901-185912.nc' 'SHA256' '5b9173a9cafffcfc685353254fad706dbc35b1266a8e02e5443c10ffaa297e21'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186001-186012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186001-186012.nc' 'SHA256' '3e1e1fcff904eae7e4a3b021ab8ad7dde6c829bb59bca73b2f628f78f1b6e78e'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186101-186112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186101-186112.nc' 'SHA256' '6575ec47ece46672d6ca441e311fca14cb19e4ebf28b19f921e090a647b74a67'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186201-186212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186201-186212.nc' 'SHA256' 'b82f00396bed3da25e0bab495e9b9fca132f13fcf7c8046b77e68c28c5881454'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186301-186312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186301-186312.nc' 'SHA256' 'b765e92873e2d673ccfe902cf5d877e8feb84d74bf34388354fe238de9d6579d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186401-186412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186401-186412.nc' 'SHA256' '5d844ca4e3a98aa0debb7476a7650ffe049cdf2f7309dcb5e1073538fd2065b9'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186501-186512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186501-186512.nc' 'SHA256' '6a09cff83ef5956f0f30badbab79b02bd17908a9ed17ed3257b9d158891478e4'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186601-186612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186601-186612.nc' 'SHA256' 'e8695f032030756eea1df298231093f66995ff8a1773cee141bdc6795de1350f'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186701-186712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186701-186712.nc' 'SHA256' '85f74e3c2d32c6a4f1a6574c8036748b724c3a44cada1f6c9623e874738c7512'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186801-186812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186801-186812.nc' 'SHA256' '5293a1f79b648b740334064640b0948734921458931ca8add0fe92562a0707c0'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186901-186912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_186901-186912.nc' 'SHA256' 'b5b31ed1806bbf0a434884c426aa7402b11001206cee047aa228b0031c8d0b38'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187001-187012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187001-187012.nc' 'SHA256' 'dc8a583c6fc41b8e6eb7f9d97b22d290784e3ab7096e44d94972b4b87a1c4c41'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187101-187112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187101-187112.nc' 'SHA256' '15f4e25d55fdc6fa7100dc674360be2ac9c58572f436f2c6c5d23064ddf8ef36'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187201-187212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187201-187212.nc' 'SHA256' '4af8a64bf4077300bd8e0a2768a5303b32a0e4bfeb9c41a90a24e017dfe6fad3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187301-187312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187301-187312.nc' 'SHA256' '4f269eb3b0b824dc79d7b0309adf0137131dc20b83b2778020ae1b22b7889189'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187401-187412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187401-187412.nc' 'SHA256' 'fdcc19ff47c888f3ad4e92a7901afc36bda81443ceb889fdc33d7cadaa82b1e3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187501-187512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187501-187512.nc' 'SHA256' 'fe340f2f3a3519c9064048eb5f877ac6c4f062ba31eb3e9ac06389b2346930e4'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187601-187612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187601-187612.nc' 'SHA256' 'fe405f988411adfc49a1882cabf57e21833da05044ac48de53b41e0c694ad69d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187701-187712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187701-187712.nc' 'SHA256' '65fdb2f8200d25eb53a78220e050aea414d250f8c42e4024c28e88d8208f06c2'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187801-187812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187801-187812.nc' 'SHA256' 'b59161212a46ae539c16f2f36b38b410c0c77238eff9bd32f43a15a81fb4b46c'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187901-187912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_187901-187912.nc' 'SHA256' '59f022d517de5a5a938b924e429c3eeb719a4bf8eae35a86f3a070fdb302e77e'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188001-188012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188001-188012.nc' 'SHA256' 'a295705825a407c1ed77ee7ef3d54212ddf07aa00b1fe24709ab720e87e2ab1f'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188101-188112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188101-188112.nc' 'SHA256' 'cdcace1cf7f8bd2b569474c91286e1a7d00d167eee4cd1e7c418315b9a39c2f5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188201-188212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188201-188212.nc' 'SHA256' '2fc45100615ad39708822f396e20e62d7a5e255f1fe7c38bc2ce747f1517b97a'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188301-188312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188301-188312.nc' 'SHA256' '55117c6bbe7e06efa32ea1b663785de4f8ed0a0bc77de51f493c6e4039a5fcc6'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188401-188412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188401-188412.nc' 'SHA256' 'ae761ee353b3e179063611fa921b95a866dc1b10d02e0268bbbb0887ffd7c782'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188501-188512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188501-188512.nc' 'SHA256' 'dd4e3e49d463d23abfa36afe7b8121ef2ae30291c20676146e6549b2cbafb551'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188601-188612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188601-188612.nc' 'SHA256' '19fe688574e3f32f68554b8c294f10d47a65f95a4b0a76f107e26e2dfbdd1ef6'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188701-188712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188701-188712.nc' 'SHA256' '0715105851a400378c237ca53486b062ff72fd10f7bf5c168de045bb5e21afa3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188801-188812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188801-188812.nc' 'SHA256' 'e477b466ac7e5d209818da76eb2f8df66f456f56978656b96d815c3be254fd83'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188901-188912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_188901-188912.nc' 'SHA256' '861077da7136632803f38ecab0a568e963de78cd18adf31f6c82653a09aaca89'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189001-189012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189001-189012.nc' 'SHA256' 'e2961a327d1c0acff76a425c02e4c34e767efb5d4c9849307a78b9d3149d1091'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189101-189112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189101-189112.nc' 'SHA256' '4e0181e19f1fb4423c39c868a9d1de2bb370b439f03960481352c654466461e4'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189201-189212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189201-189212.nc' 'SHA256' 'f6a708205436444b9bfae6b7e4ddada190e7d39419222925f1636a25ec25b9d9'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189301-189312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189301-189312.nc' 'SHA256' '7e1f9b4ce0215997baf98e2f8c4b2842bd2fff07d2fb4bd6dfe9b3bc62db732a'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189401-189412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189401-189412.nc' 'SHA256' 'de72e220f7612d7859f02094d4a07d1f87b522a95931e1de8bb50887dce6bad2'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189501-189512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189501-189512.nc' 'SHA256' 'cb98bb98e101a134de32b9bdc6c5b32cf9b11b0c350e87327abb94b6242bfe4b'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189601-189612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189601-189612.nc' 'SHA256' '36db44a0464154e42441139adfa9912ed805ec13e906992902a0588bc1c40c3f'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189701-189712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189701-189712.nc' 'SHA256' 'af0ce51ef0e312bf6d9067e3172089e7f382c95a22ce6475d55f3ef235f88fdc'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189801-189812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189801-189812.nc' 'SHA256' '98808abbce3408b0f36f060e77a7a7ec73a28b4c2b082388628e1fa4cde4af7b'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189901-189912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_189901-189912.nc' 'SHA256' '91ea1b928125647d5ca43c00429e70042ee87f48a574d3d97544f62eea95fdd7'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190001-190012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190001-190012.nc' 'SHA256' '1d6e80ef57cbbee25312db667810c80461ef34f100f10ff48d166c005a408b6f'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190101-190112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190101-190112.nc' 'SHA256' 'cea75264831ece399ce595c7647ce5b2c276809992a9116a5ee1dd164d585878'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190201-190212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190201-190212.nc' 'SHA256' 'ecb2b709976f2381bc67487e8f3b6f7b4f09b84e8619e4f3dab11afc9312a1f6'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190301-190312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190301-190312.nc' 'SHA256' '57fa4ef7ca0b2db0773a21d0dd8073112ba77fa872ecb6f2a9748ee11079068d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190401-190412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190401-190412.nc' 'SHA256' '1dc0fd5451adfe9eb226f7d7944a7e84915e22a1df6b71ff2508da90eaf46fb5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190501-190512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190501-190512.nc' 'SHA256' 'b48b6b89c5ed0eeaf1aa09c1cf3f8a15a153d777bddb6b74b6622d65ae23a783'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190601-190612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190601-190612.nc' 'SHA256' '1d41fdae11231524abff9217568c97679029715f0ee90cbd93e0be6fea2e2b38'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190701-190712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190701-190712.nc' 'SHA256' 'c34b35a301fd9fdbebe701d78471bbab0190606d8942241312b1ae36ce6f3990'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190801-190812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190801-190812.nc' 'SHA256' '10522e223404153818de0508873ae285fdac814f17396aab74010486f79b7a30'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190901-190912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_190901-190912.nc' 'SHA256' '7ae8ea04f1e05f0b7fcb0c2bf508ea992e79ae11fedb3ba93c25a8d3961b3490'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191001-191012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191001-191012.nc' 'SHA256' 'aed1805cafa460427846a9857a369ad8df3e3228bbcdffd8520f788ea600fe69'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191101-191112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191101-191112.nc' 'SHA256' '9fee9f87325ec1c17906e38d4c168956d4879166cca3a61525886216c5a74e9d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191201-191212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191201-191212.nc' 'SHA256' '51990a37591235acc228e461a73781dc88a521d283716236c57c9695d18403cf'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191301-191312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191301-191312.nc' 'SHA256' 'a1eebefc91d4621628dbb880927d193f821039b02e9232e1ebe92933cc0af476'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191401-191412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191401-191412.nc' 'SHA256' 'b4e7ac225cb0180d4502c26ed12d57b6cb48ec4ef1b31e470f2db03982055a9d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191501-191512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191501-191512.nc' 'SHA256' '551d00e6a0a2c22a59097fb069a93e78a9385b6b8d7f8c194909de2356711542'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191601-191612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191601-191612.nc' 'SHA256' '4ab0818b51491e53d5cf99fc8b3d527c1a1e9b77f8aa7e35472caa91ea0187e7'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191701-191712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191701-191712.nc' 'SHA256' 'a0a5f72758bc2a3ff74764d293db7a266ec6c3e13f95bc1d8f955603d93d75df'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191801-191812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191801-191812.nc' 'SHA256' 'd0ae55596a2c2df4fed3ca3179fd5c4f794e10e1ca5a59a7f08b0f68e73c69f6'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191901-191912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_191901-191912.nc' 'SHA256' '53baee45f5c8429cb3af9b8e45dae4c8fe38b041980d8cbe095e48160ea7b36c'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192001-192012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192001-192012.nc' 'SHA256' 'da036cf65d0bdc36b152a9009c0948e6807f446582ee400abb03d603b15e4745'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192101-192112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192101-192112.nc' 'SHA256' 'b24243c4568388d634594c48b17d0fa33e4258154de609e3ced1c770fd86fbc0'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192201-192212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192201-192212.nc' 'SHA256' 'a24ddba0cc77f29362f2e9c2b5e88bc7899ff5afd7893fa4440732ddb9a62ffa'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192301-192312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192301-192312.nc' 'SHA256' 'c11d737e8ee67a91d2ce8a64740077b8c0ca8d8a17bbd054d88843d0a138b4d6'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192401-192412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192401-192412.nc' 'SHA256' 'b8cd92358419b8d0854b80f31f75ce1ee73c1a1cabce6a31d2866042fbccc045'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192501-192512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192501-192512.nc' 'SHA256' '9a31f83311f93d0feab4abac10f37fc307c5ce4d4da6012594ee6ad4a31602f9'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192601-192612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192601-192612.nc' 'SHA256' '00a97769a0fd3205c2ffdd2b7ca131bbcefe7adcf1241aa27693a38f31d134f9'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192701-192712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192701-192712.nc' 'SHA256' '062b16440cb5d9b0511c96dda60a6a88c88a3ca75798b3a8bfaab3dc7254c7d5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192801-192812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192801-192812.nc' 'SHA256' 'e4cf70304fdb10aa2d3708db38874da7cd80edbad6179f72e9097614e6f4e1c5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192901-192912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_192901-192912.nc' 'SHA256' '29304ade122feef79395ddfe463f0f0f65c8604f4fd40be7801e800ac19745cf'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193001-193012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193001-193012.nc' 'SHA256' '6e55a505e60106ab3d3a009ce7c4999a4c299b4569cca20629efdf73c5c8041b'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193101-193112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193101-193112.nc' 'SHA256' '1f6cd42ff42b1e509ea404d3581a69c2064d21d39981e841bc2f3546df649201'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193201-193212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193201-193212.nc' 'SHA256' '8886aeea62bb316091c791fbf9088f25f582d1b5d437b5780129438de7c4cf86'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193301-193312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193301-193312.nc' 'SHA256' '4dc094421b15a5b9c08dcff9feebcb7dbe5e8c7677c30e435d747ff363a650d0'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193401-193412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193401-193412.nc' 'SHA256' 'dad247ab2a836f754e869336ba3342c80670a893f24abf755b39ca91b7b253f3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193501-193512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193501-193512.nc' 'SHA256' '9c4b3264bac5fec9e08e6741f69b9561638065b2c416902605d379d417ea01f6'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193601-193612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193601-193612.nc' 'SHA256' '7347e0fca3502e946b27f07e5805c29a935ef50400a5577de7648d5642d70a4c'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193701-193712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193701-193712.nc' 'SHA256' 'ace1f5a8c87ed1c2abeee09e2a508d1df48866c20a7feb8490742ed370c9b262'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193801-193812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193801-193812.nc' 'SHA256' 'd05394e376e42ca595bef411f39873691b31ef6e873a9f3a5e39040ce5a03aec'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193901-193912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_193901-193912.nc' 'SHA256' '22b54c41c00073477041b0e92eb0dcc5dcfb88738f198990746ca442abe5fd82'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194001-194012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194001-194012.nc' 'SHA256' 'ed00e60dc60de6280e505eb766981371a1d2ca2eeed470443ced912d8e2cac62'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194101-194112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194101-194112.nc' 'SHA256' '00cfabe142d73e6e5e2d77d1f85bd60d193e3acaaf7af9cbd761066a2dcfea65'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194201-194212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194201-194212.nc' 'SHA256' '8326ad623946eac3055ec5f2085d26de26a209b39bee31e6841dbdb1a24daf9f'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194301-194312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194301-194312.nc' 'SHA256' '8b46bd4e877f213f224d8e9b1f1ed68a71bf5f34f3db33548d3423e156a02744'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194401-194412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194401-194412.nc' 'SHA256' '1dea5cc49f081c39c18714f51d8c386670b27b53e84d39ededf001356b7b400d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194501-194512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194501-194512.nc' 'SHA256' 'ac852f90a2cfc0ed3543d6bb7b1aec14d80306215e544c81de2f7fc1b84250dd'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194601-194612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194601-194612.nc' 'SHA256' '4865c86c5fdc5b5b24020568b0175970057bd9379d9374c1f9e178ce76ab7a81'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194701-194712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194701-194712.nc' 'SHA256' '4fae7bea6c225884aad5bcf3364fb32ffb4308dcc5fa2c0b98689adaeac4e9b2'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194801-194812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194801-194812.nc' 'SHA256' 'e4159561d31ed60dccbeb84e15525f231c2207cbe85bf0e4115126d9b3ec5325'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194901-194912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_194901-194912.nc' 'SHA256' '29b3b3b974835a0fc6fccfe72c03fb7ccca7f25c24231f91103bff08aab90ac5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195001-195012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195001-195012.nc' 'SHA256' '072aa993f1da7cca63108b5958872727349e3d89b99647e47ed9bf7b350b8066'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195101-195112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195101-195112.nc' 'SHA256' '03cbe16c45b0da77cdfb4bf41aaddb7131224f185d88b8b753f55529f00fefb3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195201-195212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195201-195212.nc' 'SHA256' '4554054cf41a1f928f3b08d1d7fed6a4167ccae3e29606fa803cdb52e4271100'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195301-195312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195301-195312.nc' 'SHA256' 'ef611963c9aad7b7925d2829483cf07620625e14068fab54e6a20c5283d82e09'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195401-195412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195401-195412.nc' 'SHA256' '16243833e21c763c5c96ca7d2c5268b818eaa50bb79fd0b40a0498ba43a47765'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195501-195512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195501-195512.nc' 'SHA256' '76183f92f6426496d95c28d93acf8553cd7ec5585045c057390fc53ca4476798'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195601-195612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195601-195612.nc' 'SHA256' '98c0ec32081b45c09df37b1b97a5e86779d2880dc48c579194bae6222a1f4891'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195701-195712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195701-195712.nc' 'SHA256' '057ec533272d7157be9ae997d9bbc71148b07cf8d6265af59a6ff40d8621bc68'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195801-195812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195801-195812.nc' 'SHA256' 'f8155bb6738bc61ec04357d9cdd156f43f0735b9ce72158f9847daa758dfde18'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195901-195912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_195901-195912.nc' 'SHA256' 'e1bca9d6cc360ba510dbd7a75c20c8714c1edcc0e29486178dba4c49ff477997'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196001-196012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196001-196012.nc' 'SHA256' 'efeeba02c63c94cb4f43b76aa8404117f66665b4ba1d73807517a251b92414a3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196101-196112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196101-196112.nc' 'SHA256' '15a301b400d2e7b3741365d34e8722921c84d60ef4d16d0c28aa8279e9d5102c'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196201-196212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196201-196212.nc' 'SHA256' '2f7f0833e7eb7abc710526cb12fad64839f055c8506b963f82b4a662f562ce9c'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196301-196312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196301-196312.nc' 'SHA256' '45d4ea58968ec8396d29b036d881cb35d4b2a29902a468dffb32458318ad107a'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196401-196412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196401-196412.nc' 'SHA256' '815b1168f19d39ce10f940f5a726b771bc895026dc0552801f18705e445256e9'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196501-196512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196501-196512.nc' 'SHA256' '563510b4c1a0deb92085e0791f9463be9a7e1598189dc268b9beee0233aaae20'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196601-196612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196601-196612.nc' 'SHA256' 'b5f9e3b42edd7b1701f51a1b73de6002446fac3edd190bc91e4b54a584aa750a'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196701-196712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196701-196712.nc' 'SHA256' '5552dcea6187d0e4c4e9296ce663edd2e54f3f4b5e864deea29949c9b6cec832'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196801-196812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196801-196812.nc' 'SHA256' 'b2750348ad99fd44798336eb42df4764fe64afe957ea6aa9f3f80c5a3f1012ef'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196901-196912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_196901-196912.nc' 'SHA256' 'a2af1d75d9297fc076957c6886fc36f04fc8659a15533c567b6ccb36181d8823'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197001-197012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197001-197012.nc' 'SHA256' '9b3c3c8501ffc53f904bf4ea1fe918abf2a539d14aafa0f7860119a99f971832'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197101-197112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197101-197112.nc' 'SHA256' 'fd9c93c2c481cc4ae647a709b7e02a4f99787668cfe79f29752da40b9d45ac7d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197201-197212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197201-197212.nc' 'SHA256' '477ec070d2419a1690d667cae07814fb6071f7b79c71b4655b40fef7592103a7'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197301-197312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197301-197312.nc' 'SHA256' '5479a255094bf8edb1fb2fdd59e6e3d43c88591344bbcd3871510f18847ebdc3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197401-197412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197401-197412.nc' 'SHA256' '7babbe003aab5191974b114d57ef6c99ea18f6e8f5d07c8b871ec3f92e058443'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197501-197512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197501-197512.nc' 'SHA256' '2fbe63619728d8578ba26d61fbe29203a3453600dd1b73abccb44063911ec141'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197601-197612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197601-197612.nc' 'SHA256' '8a5d63d6c2ffb2ffde132f190a53b04e5daeccddf7343993cd9d20eb81d79551'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197701-197712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197701-197712.nc' 'SHA256' '4a78f7c82d6a6a018077c728e6f6503f67610d68326b59bd1e029534ff3f2a90'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197801-197812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197801-197812.nc' 'SHA256' '7cff0617d3067e39032ce5d5d706274faa85c431d75d339c00b6267bc2cee1d8'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197901-197912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_197901-197912.nc' 'SHA256' '41507d6b674d90073cd400439c6d47a1156a16fcf93e6e7ee77ae92ad8bf64a7'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198001-198012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198001-198012.nc' 'SHA256' '6abd3e4cf657375dea2df6d290c71eb0dbcc1005e1ca6e17d61fc6445cb426f5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198101-198112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198101-198112.nc' 'SHA256' '39ba18119589e90776c343ae2560dc3ea9106ad6fd905c43eb4eb97cee1e4c57'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198201-198212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198201-198212.nc' 'SHA256' '44bd43373e9d813fc1f28349f9cb1e1c24ba523e95ce9525875849efc3e3e902'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198301-198312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198301-198312.nc' 'SHA256' '1b9c7de624414ad65cba15cf8c87f6e1740f9ecff1cd3d585bfca390b7d6b3d3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198401-198412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198401-198412.nc' 'SHA256' 'bdbce3479b13d8ae6f62ccc98f4dc32664a7a0cf56a3d8be17fb93d3aea56dd4'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198501-198512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198501-198512.nc' 'SHA256' '85ae5cd4e4e426910322413fd45fd0452b05c32b81662e7a7b393de877350a87'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198601-198612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198601-198612.nc' 'SHA256' 'f83f57b250cdbb19791e2eb81904c0996bcfba641492963bb0a3126ee2ff6c3d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198701-198712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198701-198712.nc' 'SHA256' '0561f94075676620b80f164c6646b288b91f9d154b9f044b6d1539e0570eb5eb'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198801-198812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198801-198812.nc' 'SHA256' 'e0c3ec3ad86ea6c91efb74a4872db8dac11d4a21d98dbca3415fee8f3a19a2f1'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198901-198912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_198901-198912.nc' 'SHA256' '375b8eba77255f76844a7e83c3bcae10b32b9b91f57377e4066deb6a470d7291'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199001-199012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199001-199012.nc' 'SHA256' '894be7cb7afbbccf2589895b7b98255193487b7224b98d9e9c89404c9c12c5f6'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199101-199112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199101-199112.nc' 'SHA256' '16733e000b39560d6aa5ae8cecbf02081c8cee8b89df4fa29663d35f143affde'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199201-199212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199201-199212.nc' 'SHA256' '383ffdf06cc69fa0373f8b984a256eda6da4419841c370b1a5225bc62508805a'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199301-199312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199301-199312.nc' 'SHA256' 'c910151d2dbade37c8cf83c92ce1333f50fec0f6457c03316e0bfb3375c25539'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199401-199412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199401-199412.nc' 'SHA256' 'cbfb3d0b95349e51c6caff2989d688a4abccad40a72b0787d64953225b9985e5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199501-199512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199501-199512.nc' 'SHA256' 'd4dc72068dde5a527c0ce4012751e87bc0568e44ff01dd838fa5cf2c87bb560d'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199601-199612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199601-199612.nc' 'SHA256' '73768d331dadf871dab6509a91b26075e9a02ff4b09ef99d59b8f24180c680cd'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199701-199712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199701-199712.nc' 'SHA256' 'e4422d133ea9cab2a7624406e7a868bf0fc40d5e501a1f659b69400ad23e3ddb'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199801-199812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199801-199812.nc' 'SHA256' '98f059ec5ddad94a2d6454c66065c004d6006e7dcc33ef94d241319ab6dc8c7a'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199901-199912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_199901-199912.nc' 'SHA256' '7d5984c9b1f11d8853ec9bb2b25fafe03d35ece5a98d79f833d129a1b8890abc'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200001-200012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200001-200012.nc' 'SHA256' '0122ea684e407f0c0badfc53b31cc9407a5122785b22c52af2539516858800d3'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200101-200112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200101-200112.nc' 'SHA256' 'c8e7d2e073b35375fb1a978b1f211cdda87a1145f975f2f21c4a7e799a52584c'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200201-200212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200201-200212.nc' 'SHA256' '0ed7fe33abc253ef3b5bcaf1deef4c00e20c9fac0012ef2c283277f2c5b4b945'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200301-200312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200301-200312.nc' 'SHA256' '6a0e1060d93d09de974772e409a647828724ee2ee8e7a4e38fc77982e261c9bf'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200401-200412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200401-200412.nc' 'SHA256' '840244ef2f72e98abd71ee5bfc4f3175448ed9aff82e78d92e40e7ef31d093f7'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200501-200512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200501-200512.nc' 'SHA256' 'e5e20dc78c296e0441018fafd162fe51baec88aa898efb952e33a74f9516283b'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200601-200612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200601-200612.nc' 'SHA256' 'b464ec31ce18de7da9ed778a7d74cbdec55d6016587e64f3ce33b5798b8cfeae'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200701-200712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200701-200712.nc' 'SHA256' '388a686f95a9bd9596e6231f62f0e97544cb836db5582c6c69101df979c00b96'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200801-200812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200801-200812.nc' 'SHA256' '60516e1c76e4716977e00ab265a1efcea74e750fd13d36f4a311ec6db2aa34a9'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200901-200912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_200901-200912.nc' 'SHA256' 'aaf6790e34d8ee877eaff0a8da2b7b0d744ee6d430c006494f0679512e05a886'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201001-201012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201001-201012.nc' 'SHA256' 'ef39190d224323deff7b515e8a21e1b990ab6675c517120dce885eb66fecec20'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201101-201112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201101-201112.nc' 'SHA256' '0b26443096f381e8ffc4f856b9d90ba5a43732b2bcabc67405f97e9aedb9910a'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201201-201212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201201-201212.nc' 'SHA256' 'b70e15107afe2c72251e16e6afbe7920ec90f544b9f83f255f976a98a2851cd5'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201301-201312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201301-201312.nc' 'SHA256' 'bda9dfbe23aad77e4c1bab05049d45a9f6ed63c405ab027e6186318f98e0225b'
'thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201401-201412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Omon/thetaoga/gn/v20200918/thetaoga_Omon_EC-Earth3_historical_r1i1p1f1_gn_201401-201412.nc' 'SHA256' '08764478e7d178f5b43c77d5860b86925a3ad59defbd44e5e2025b3df098daac'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 165 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
